### ISSUE TITLE
Issue project upload on current directory

### ISSUE THREAD

**Issue by stephanemartin** [Neotys-Labs/neoload-cli#125]
### How to reproduce
$ neoload login <your_token>
$ neoload test-settings use <your_test_settings>
$ cd ~/neoload_projects/v7.7/Sample_Project

$ neoload project up

### Actual Results:
Error: Error 400 during the request: POST https://neoload-files.saas.neotys.com/v2/tests/f5a3ea7f-c509-4437-8228-b818bac341ed/project

### Expected Results:
{
  "projectId": "602fb38ad9ded72fd411634e",
  "projectName": "Sample_Project",
  "projectVersion": "8.2",
  "asCodeFiles": [],
  "scenarios": [
    {
      "scenarioName": "WANImpact Local",
      "scenarioDuration": 600,
      "scenarioVUs": 35,
      "scenarioSource": "Sample_Project.nlp"
    }
  ]
}

**Comment by guillaumebert** [comment]
Issue fixed and released in CLI v1.2.1 See [pypi.org](https://pypi.org/project/neoload).
