### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by theqmguy** [Neotys-Labs/neoload-cli#139]
Hello,

The documentation aroung test-settings suggests I can specify a single zone and the number of LGs
--zone mine --lgs 3

However, you can actually have controller and LGs spread across multiple zones in Neoload Web, this is also possible in the CLI
--zone my_zone --lgs your_zone:2, their_zone:3

...however this example is missing from the documentation.  Can useful examples such as this be added, many thanks

**Comment by paulsbruce** [comment]
Agreed, as discussed over email, we should update the docs to reflect actual usage example.

**Comment by guillaumebert** [comment]
Documentation has been improved with this example. Thanks
