### ISSUE TITLE
Issue running CLI fromJenkins

### ISSUE THREAD

**Issue by jlupisella** [Neotys-Labs/neoload-cli#196]
Getting this error when kicking off a build in Jenkins:
TypeError: wait() Got an unexpected keyword argument 'data'

Neoload Data is not displaying in Jenkins

Details with screen shots are attached here: 
[Word Doc for CLI error description.docx](https://github.com/Neotys-Labs/neoload-cli/files/9235881/Word.Doc.for.CLI.error.description.docx)

**Comment by guillaumebert** [comment]
This is a bug. It has been fixed by this PR : https://github.com/Neotys-Labs/neoload-cli/pull/198
