### ISSUE TITLE
Report problem when several tests run in parallel

### ISSUE THREAD

**Issue by ahellec** [Neotys-Labs/neoload-cli#203]
Hello,
when I run several tests: A, B, C with 3 jobs on jenkins
Tests A and B retrieve the report from test C.
If I use the command:
neoload test-results use <result_id>
and after
neoload report ...
Often it retrieves the wrong report.

Can you modify the "neoload report" command with a "result_id" parameter?

best regards

**Comment by guillaumebert** [comment]
Hello,
You can get the report of a specific Test Result by giving its name or id as argument [NAME].
`Usage: neoload report [OPTIONS] [NAME]`
Examples:

- `neoload report --template builtin:transactions-csv 7b6fce8d-ad8a-4969-be98-1dd681888ef0`
- `neoload report --template builtin:transactions-csv "My Test Result Name #1"`

**Comment by ahellec** [comment]
Thanks a lot it works
If you can put an example with the result id in the documentation it's perfect
