### ISSUE TITLE
neoload workspaces use  Issues

### ISSUE THREAD

**Issue by koenry** [Neotys-Labs/neoload-cli#221]
Using `neoload workspaces use "Default Workspace"` works but using a workspace with a single word wrapped in quotes does not. 
A workaround would be to remove the quotes and use it like `neoload workspaces use oneword`   using `neoload workspaces use "oneword"`  gives an error 403 ,  {code - 105  message - 'Entity not in the specified workspace'}  This issue was only tested with Github actions.

**Comment by koenry** [comment]
Also when using with github actions 
neoload login --url http://your-onpremise-neoload-api.com/ --workspace "Default Workspace" your-token 
--workspace will not work with an error that --workspace is not a neoload command, but if you add it before --url flag it seems to work.

**Comment by stephanemartin** [comment]
Sorry I can't reproduce this issue
![image](https://github.com/Neotys-Labs/neoload-cli/assets/3063721/5cb7a7a3-5c7e-472c-aa03-fc87ca981d25)

**Comment by stephanemartin** [comment]
![image](https://github.com/Neotys-Labs/neoload-cli/assets/3063721/15e606f2-0763-43c9-a865-d69a5e7fb0f5)

**Comment by stephanemartin** [comment]
![image](https://github.com/Neotys-Labs/neoload-cli/assets/3063721/f524eeb9-91ca-4cc6-931d-f50e36c99460)

**Comment by stephanemartin** [comment]
![image](https://github.com/Neotys-Labs/neoload-cli/assets/3063721/49083265-a841-4272-9f17-783422cf47a5)

**Comment by koenry** [comment]
Hello,

Thank you for your reply, I only encountered this issue from a github pipeline, might be due to yaml formatting the cli command incorrectly somehow. It's good to know it's working as intended! Have a nice day.

Best regards

**Comment by stephanemartin** [comment]
Thanks for your feed back

**Comment by guillaumebert** [comment]
I didn't reproduced neither when executing the example github action:

This works:
```
- name: "Prepare NeoLoad test"
run: >
    neoload login --url ${{ github.event.inputs.api_url }} --workspace "Default Workspace" ${{ github.event.inputs.token }}
```
And this also works:
```
   - name: "Set Workspace"
   run: neoload workspaces use MyWorkspace
```

**Comment by koenry** [comment]
Hi!
  
  https://github.com/koenry/nl-cli-bug-reproduce/actions/runs/5488776419/jobs/10002087883 This is how its reproduced from my side.

**Comment by guillaumebert** [comment]
Your command is invalid according to the help because you added the option "--workspace" after the [TOKEN]...

`Usage: neoload login [OPTIONS] [TOKEN]`
