### ISSUE TITLE
No Result Found to Publish : SLA Reporting via JUnit 

### ISSUE THREAD

**Issue by bcouavoux** [Neotys-Labs/neoload-cli#99]
Hello,
We have a problem for publishing the SLA Reporting via JUnit.

**The pipeline used :**

- task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla

 - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true

**The "Get the junit SLA report" step work well :**
![image](https://user-images.githubusercontent.com/52322253/94266575-a33b9b00-ff3a-11ea-96e0-b4ccddf3d7b2.png)

**But we have this error message for the publish step:**
![image](https://user-images.githubusercontent.com/52322253/94266519-8ef79e00-ff3a-11ea-9ec9-28ba0d6f43ac.png)

**Comment by bcouavoux** [comment]
An ls command show the xml file at the "Get the junit SLA report" step :
![image](https://user-images.githubusercontent.com/52322253/94268856-0ed33780-ff3e-11ea-9cf0-580615ab3f5c.png)
So the file is present in the folder. It seems to be a problem with the junit publish step .. Do you have the same problem ?

**Comment by guillaumebert** [comment]
The publish step ended with success because the report is empty, there is no success nor failures.
I guess your Neoload test does not contains any SLA. According to the Help page, the junitsla option "Output SLA results to a file with junit format"

**Comment by bcouavoux** [comment]
Our test has an SLA, we can see it in the SLA tab on the neoload web page : 
![image](https://user-images.githubusercontent.com/52322253/94410894-344b8580-0178-11eb-89d7-577449c72f7a.png)

**Comment by guillaumebert** [comment]
Indeed, only "Per interval" and "Per test" SLA are output to the Junit report.
The team planned to add Global SLA to the Junit report. This should be available soon.

**Comment by guillaumebert** [comment]
Fixed in version 1.1.5. Published on [pypi](https://pypi.org/project/neoload).
